### ISSUE TITLE
re-enable stage2 tests

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1364]
I apologize, I have merged `async-fs` branch even though there are some race conditions in the stage2 tests. Here's the situation:

 * [x] #1363 is my number one priority. I need to resolve this before I solve the race conditions in the stage2 tests.
 * [x] #1260 is also very important. I've typed `catch unreachable` far too many times, and I understand coroutines enough now that I need to iterate on the design.
 * [x] Next, in order to solve the problems, I want stack traces on Windows. So I'll do that. #721 
 * [x] Then I'll add some debug runtime safety features where incorrectly resuming a coroutine, or canceling it twice, etc, will print the source location of where the coroutine was first resumed, or first cancelled, or at least just print which coroutine it is. This requires stack traces, hence the previous bullet point.
 * [ ] With these tools, it should be straightforward to solve the issues. My goal is to not do anything clever to solve these bugs. Rely exclusively on the tools/safety features zig provides in order to resolve the problems. If that is not possible, improve zig's safety features and tools.
 * [x] A semi-related problem is that CI tests are close to the limit. Sometimes AppVeyor tests fail due to taking longer than 1 hour. 1 hour is a reasonable amount of time for all tests to complete. So I will do something to make CI tests pass more consistently. Perhaps do some caching in stage1. #1416

**Comment by andrewrk** [comment]
I disabled stage2 tests on all targets. This issue is now postponed until after 0.3.0.

**Comment by andrewrk** [comment]
With the self-hosted reboot, this issue is no longer relevant. There's a new test harness and new test cases.
