### ISSUE TITLE
Tracker: Documentation

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1366]
This issue is tracking all [documentation](https://ziglang.org/documentation/master/) items that are marked TODO until completion.

PRs related to documentation can add this issue number to the end of the branch.
Example: `docs-implicitcast-issue1366`

* [ ] Implicit Cast: Arrays
* [ ] Implicit Cast: Optionals
* [ ] Implicit Cast: T to E!T
* [ ] Implicit Cast: E to E!T
* [ ] Implicit Cast: comptime_int to *const integer
* [ ] Implicit Cast: comptime_float to *const float
* [ ] Implicit Cast: compile-time known numbers
* [ ] Implicit Cast: union to enum
* [ ] Implicit Cast: enum to union
* [ ] Implicit Cast: T to *T when @sizeOf(T) == 0
* [ ] Implicit Cast: undefined
* [ ] Implicit Cast: T to *const T
* [ ] Peer Type Resolution
  PR: #1367
* [ ] `this`
* [ ] Assembly
* [ ] Atomics
* [ ] Out of Bounds Float To Integer Cast
* [ ] Memory
* [ ] Root Source File
* [ ] Zig Test
* [ ] Zig Build System

**Comment by andrewrk** [comment]
Duplicate of #367
