### ISSUE TITLE
Tracking issue for compiler_rt ARM compatibility

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#14634]
### Zig Version

master

### Steps to Reproduce and Observed Behavior

Based on https://gist.github.com/harieamjari/61aa4420ae4ded5e86f5143e46d93573 by user @ @harieamjari the list of ARM run-time functions to double-check

Preparation for audit of compiler_rt in #1504.

```
The functions declared here is based on the document, number,
 * "ARM IHI 0043D, current through ABI release 2.09", which
 * defines the run-time helper-function ABI for programs written
 * in ARM-Thumb assembly language, C, and C++.
```

/* Standard double precision floating-point arithmetic helper functions */
- [ ] extern double __aeabi_dadd(double, double);
- [ ] extern double __aeabi_ddiv(double n, double d);
- [ ] extern double __aeabi_dmul(double, double);
- [ ] extern double __aeabi_drsub(double x, double y);
- [ ] extern double __aeabi_dsub(double x, double y);

/* double precision floating-point comparison helper functions */
- [ ] extern void __aeabi_cdcmpeq(double, double);
- [ ] extern void __aeabi_cdcmple(double, double);
- [ ] extern void __aeabi_cdrcmple(double, double);
- [ ] extern int __aeabi_dcmpeq(double, double);
- [ ] extern int __aeabi_dcmplt(double, double);
- [ ] extern int __aeabi_dcmple(double, double);
- [ ] extern int __aeabi_dcmpge(double, double);
- [ ] extern int __aeabi_dcmpgt(double, double);
- [ ] extern int __aeabi_dcmpun(double, double);

/* Standard single precision floating-point arithmetic helper functions */
- [ ] extern float __aeabi_fadd(float, float);
- [ ] extern float __aeabi_fdiv(float n, float d);
- [ ] extern float __aeabi_fmul(float, float);
- [ ] extern float __aeabi_frsub(float x, float y);
- [ ] extern float __aeabi_fsub(float x, float y);

/* Standard single precision floating-point comparison helper functions */
- [ ] extern void __aeabi_cfcmpeq(float, float);
- [ ] extern void __aeabi_cfcmple(float, float);
- [ ] extern void __aeabi_cfrcmple(float, float);
- [ ] extern int __aeabi_fcmpeq(float, float);
- [ ] extern int __aeabi_fcmplt(float, float);
- [ ] extern int __aeabi_fcmple(float, float);
- [ ] extern int __aeabi_fcmpge(float, float);
- [ ] extern int __aeabi_fcmpgt(float, float);
- [ ] extern int __aeabi_fcmpun(float, float);

/* Standard floating-point to integer conversions */
- [ ] extern int __aeabi_d2iz(double);
- [ ] extern unsigned __aeabi_d2uiz(double);
- [ ] extern long long __aeabi_d2lz(double);
- [ ] extern unsigned long long __aeabi_d2ulz(double);
- [ ] extern int __aeabi_f2iz(float);
- [ ] extern unsigned __aeabi_f2uiz(float);
- [ ] extern long long __aeabi_f2lz(float);
- [ ] extern unsigned long long __aeabi_f2ulz(float);

/* Standard conversions between floating types */
- [ ] extern float __aeabi_d2f(double);
- [ ] extern double __aeabi_f2d(float);
- [ ] extern float __aeabi_h2f(short hf);
- [ ] extern float __aeabi_h2f_alt(short hf);
- [ ] extern short __aeabi_f2h(float f);
- [ ] extern short __aeabi_f2h_alt(float f);
- [ ] extern short __aeabi_d2h(double);
- [ ] extern short __aeabi_d2h_alt(double);

/* Standard integer to floating-point conversions */
- [ ] extern double __aeabi_i2d(int);
- [ ] extern double __aeabi_ui2d(unsigned);
- [ ] extern double __aeabi_l2d(long long);
- [ ] extern double __aeabi_ul2d(unsigned long long);
- [ ] extern float __aeabi_i2f(int);
- [ ] extern float __aeabi_ui2f(unsigned);
- [ ] extern float __aeabi_l2f(long long);
- [ ] extern float __aeabi_ul2f(unsigned long long);

/* Long long functions */
- [ ] extern long long __aeabi_lmul(long long, long long);
- [ ] extern lldiv_t __aeabi_ldivmod(long long n, long long d);
/* ulldiv_t might be unsupported */
- [ ] extern ulldiv_t __aeabi_uldivmod(unsigned long long n, unsigned long long d);
- [ ] extern long long __aeabi_llsl(long long, int);
- [ ] extern long long __aeabi_llsr(long long, int);
- [ ] extern int __aeabi_lcmp(long long, long long);
- [ ] extern int __aeabi_ulcmp(unsigned long long, unsigned long long);

/* Integer (32/32 -> 32) division functions */
- [ ] extern int __aeabi_idiv(int numerator, int denominator);
- [ ] extern unsigned __aeabi_uidiv(unsigned numerator, unsigned denominator);
typedef struct { int quot; int rem; } idiv_return;
typedef struct { unsigned quot; unsigned rem; } uidiv_return;
- [ ] extern idiv_return __aeabi_idivmod(int numerator, int denominator);
- [ ] extern uidiv_return __aeabi_uidivmod(unsigned numerator, unsigned denominator);

/* Division by zero */
- [ ] extern int __aeabi_idiv0(int return_value);
- [ ] extern long long __aeabi_ldiv0(long long return_value);

/* Unaligned memory access */
- [ ] extern int __aeabi_uread4(void *address);
- [ ] extern int __aeabi_uwrite4(int value, void *address);
- [ ] extern long long __aeabi_uread8(void *address);
- [ ] extern long long __aeabi_uwrite8(long long value, void *address);

/* Memory copying */
- [ ] extern void __aeabi_memcpy8(void *dest, const void *src, size_t n);
- [ ] extern void __aeabi_memcpy4(void *dest, const void *src, size_t n);
- [ ] extern void __aeabi_memcpy(void *dest, const void *src, size_t n);
- [ ] extern void __aeabi_memmove8(void *dest, const void *src, size_t n);
- [ ] extern void __aeabi_memmove4(void *dest, const void *src, size_t n);
- [ ] extern void __aeabi_memmove(void *dest, const void *src, size_t n);

/* Memory clearing and setting */
- [ ] extern void __aeabi_memset8(void *dest, size_t n, int c);
- [ ] extern void __aeabi_memset4(void *dest, size_t n, int c);
- [ ] extern void __aeabi_memset(void *dest, size_t n, int c);
- [ ] extern void __aeabi_memclr8(void *dest, size_t n);
- [ ] extern void __aeabi_memclr4(void *dest, size_t n);
- [ ] extern void __aeabi_memclr(void *dest, size_t n);

### Expected Behavior

filler

**Comment by matu3ba** [comment]
The official documentation is found here https://github.com/ARM-software/abi-aa/releases and the runtime abi here: https://github.com/ARM-software/abi-aa/blob/2982a9f3b512a5bfdc9e3fea5d3b298f9165c36b/rtabi32/rtabi32.rst

**Comment by matu3ba** [comment]
See also #15468.

**Comment by matu3ba** [comment]
ARM-only ones:
| Done | Name      | a   | b   | Out  | Comment               |
| ---- | --------  | --- | --- | -----| ----------------------|
| |                |     |     |      | **Float Comparison**  |
|✗|__aeabi_cfcmpeq | f32 | f32 | void | `a == b` result in PSR ZC flags[^PSRZC] |
|✗|__aeabi_cfcmple | f32 | f32 | void | `a <= b` result ..    |
|✗|__aeabi_cfrcmple| f32 | f32 | void | `b <= a` ..           |
|✗|__aeabi_cdcmpeq | f64 | f64 | void | `a == b` ..           |
|✗|__aeabi_cdcmple | f64 | f64 | void | `a <= b` ..           |
|✗|__aeabi_cdrcmple| f64 | f64 | void | `b <= a` ..           |
| |                |     |     |      | **Float Arithmetic**  |
|✗|__aeabi_frsub   | f64 | f64 | f64  | `b - a`               |
|✗|__aeabi_drsub   | f64 | f64 | f64  | ..                    |
| |                |     |     |      | **Special**           |
|✓|__aeabi_read_tp |  ∅  |  ∅  | *u8  | ret tls pointer       |
|✗|__aeabi_idiv0   | i32 |  ∅  | i32  | div by 0 modifier     |
|✗|__aeabi_ldiv0   | i64 |  ∅  | i64  | div by 0 modifier     |
| |                |     |     |      | **Unaligned memory access** |
|✗|__aeabi_uread4  |[*]u8|  ∅  | i32  | ret value read        |
|✗|__aeabi_uwrite4 | i32 |[*]u8| i32  | ret value written     |
|✗|__aeabi_uread8  |[*]u8|  ∅  | i64  | ..                    |
|✗|__aeabi_uwrite8 | i64 |[*]u8| i64  | ..                    |

| Done | Name      | a   | b   | c  | Comment                 |
| ---- | --------  | --- | --- | -----| ----------------------|
| |                |     |     |      | **Memory copy, move and set** |
|✓|__aeabi_memcpy8 |[*]u8|[*]u8| usize| *dest, *src, size     |
|✓|__aeabi_memcpy4 |[*]u8|[*]u8| usize| ..                    |
|✓|__aeabi_memcpy  |[*]u8|[*]u8| usize| ..                    |
|✓|__aeabi_memmove8|[*]u8|[*]u8| usize| *dest, *src, size     |
|✓|__aeabi_memmove4|[*]u8|[*]u8| usize| ..                    |
|✓|__aeabi_memmove |[*]u8|[*]u8| usize| ..                    |
|✓|__aeabi_memset8 |[*]u8|usize| i32  | *dest, size, char     |
|✓|__aeabi_memset4 |[*]u8|usize| i32  | ..                    |
|✓|__aeabi_memset  |[*]u8|usize| i32  | ..                    |
|✓|__aeabi_memclr8 |[*]u8| u32 | usize| *dest, size           |
|✓|__aeabi_memclr4 |[*]u8| u32 | usize| ..                    |
|✓|__aeabi_memclr  |[*]u8| u32 | usize| ..                    |
|✓|__aeabi_uwrite8 | i64 |[*]u8| i64  | ..                    |

Note: If having identical implementation [including besides function signature], routines are documented in #15675 and #15676.

**Comment by andrewrk** [comment]
I'm not seeing the value in this tracking issue.
