### ISSUE TITLE
compiler_rt: Tracking Issue PPC Routines

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#16057]
As far as I know, there is no specification and the "libgcc code is the specification".

From`libgcc/config/rs6000/float128-ifunc.c` and those looks to be the complete list judging from what we already have in compiler_rt:

```
Generally for newer platforms (without flags to overwrite behavior):
float = f32
double = f32
TFtype = f128
SItype_ppc  = i32
USItype_ppc = u32
DItype_ppc  = i64
UDItype_ppc = u64
DSItype_ppc = u64
TItype_ppc  = i128
UTItype_ppc = u128
IBM128_TYPE = ??TODO!!
TCtype = (real:f128, im:f128)
CMPtype = i32
```

- [x] TFtype __addkf3 (TFtype, TFtype)
- [x] TFtype __subkf3 (TFtype, TFtype)
- [x] TFtype __mulkf3 (TFtype, TFtype)
- [x] TFtype __divkf3 (TFtype, TFtype)
- [x] TFtype __negkf2 (TFtype)
- [x] TFtype __powikf2 (TFtype, SItype_ppc)
- [x] CMPtype __eqkf2 (TFtype, TFtype)
- [x] CMPtype __nekf2 (TFtype, TFtype)
- [x] CMPtype __gekf2 (TFtype, TFtype)
- [x] CMPtype __gtkf2 (TFtype, TFtype)
- [x] CMPtype __lekf2 (TFtype, TFtype)
- [x] CMPtype __ltkf2 (TFtype, TFtype)
- [x] CMPtype __unordkf2 (TFtype, TFtype)
- [x] TFtype __extendsfkf2 (float)
- [x] TFtype __extenddfkf2 (double)
- [x] float __trunckfsf2 (TFtype)
- [x] double __trunckfdf2 (TFtype)
- [x] SItype_ppc __fixkfsi (TFtype)
- [x] DItype_ppc __fixkfdi (TFtype)
- [x] USItype_ppc __fixunskfsi (TFtype)
- [x] UDItype_ppc __fixunskfdi (TFtype)
- [x] TFtype __floatsikf (SItype_ppc)
- [x] TFtype __floatdikf (DItype_ppc)
- [x] TFtype __floatunsikf (USItype_ppc)
- [x] TFtype __floatundikf (UDItype_ppc)
- [ ] IBM128_TYPE __extendkftf2 (TFtype) => (TFtype => IBM128_TYPE)
- [ ] TFtype __trunctfkf2 (IBM128_TYPE) => (IBM128_TYPE => TFtype)
- [x] TCtype __mulkc3 (TFtype, TFtype, TFtype, TFtype)
- [x] TCtype __divkc3 (TFtype, TFtype, TFtype, TFtype)
- [x] FLOAT128_HW_INSNS_ISA3_1 (no handling)
  * [x] TFtype __floattikf (TItype_ppc)
  * [x] TFtype __floatuntikf (UTItype_ppc)
  * [x] TItype_ppc __fixkfti (TFtype)
  * [x] UTItype_ppc __fixunskfti (TFtype)

libquadmath compatible math function signatures:

Math routines:
- [x] ceilq
- [x] cosq
- [x] expq
- [x] exp2q
- [x] fabsq
- [x] floorq
- [x] fmaq
- [x] fmaxq
- [x] fminq
- [x] fmodq
- [x] logq
- [x] log10q
- [x] log2q
- [x] roundq
- [x] sinq
- [x] sincosq
- [x] sqrtq
- [x] tanq
- [x] truncq

Documentation is maintained in https://github.com/matu3ba/matu3ba.github.io/tree/master/crt until review or I have a better place for it to reduce maintenance churn.
