### ISSUE TITLE
compiler_rt: Tracking Issue SPARC Routines

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#16099]
SYSTEM V APPLICATION BINARY INTERFACE
SPARC Processor Supplement Third Edition

Routines are used in 'SparcISelLowering.cpp' in LLVM. Docs are not very specific on which are needed and glibc is unreadable, so I'm not yet sure if aliasing hardware instructions is also necessary like in ARM. **TODO clarify**

Support Routines
Besides operating system services, libsys contains the following processor-specific support routines.

Figure 6-1: libsys Support Routines
These should be the regular SPARC symbols and the other the 64bit symbols.

- [ ] _Q_add
- [ ] _Q_cmp
- [ ] _Q_cmpe
- [ ] _Q_div
- [ ] _Q_dtoq
- [ ] _Q_feq
- [ ] _Q_fge
- [ ] _Q_fgt
- [ ] _Q_fle
- [ ] _Q_flt
- [ ] _Q_fne
- [ ] _Q_itoq
- [ ] _Q_mul
- [ ] _Q_neg
- [ ] _Q_qtod
- [ ] _Q_qtoi
- [ ] _Q_qtos
- [ ] _Q_qtou
- [ ] _Q_sqrt
- [ ] _Q_stoq
- [ ] _Q_sub
- [ ] _Q_utoq
- [ ] .div
- [ ] __dtou: conversion (unused in llvm)
- [ ] __ftou: conversion (unused in llvm)
- [ ] .mul
- [ ] .rem
- [ ] .stret1
- [ ] .stret2
- [ ] .stret4
- [ ] .stret8
- [ ] .udiv
- [ ] .umul
- [ ] .urem: There is no rem or urem in libc 64 psABI

libc 64 psABI (currently implemented in compiler_rt):
- [x] _Qp_add
- [x] _Qp_cmp
- [ ] _Qp_cmpe
- [x] _Qp_div
- [x] _Qp_dtoq
- [x] _Qp_feq
- [x] _Qp_fge
- [x] _Qp_fgt
- [x] _Qp_fle
- [x] _Qp_flt
- [x] _Qp_fne
- [x] _Qp_itoq
- [x] _Qp_mul
- [ ] _Qp_neg
- [x] _Qp_qtod
- [x] _Qp_qtoi
- [x] _Qp_qtos
- [x] _Qp_qtoui
- [x] _Qp_qtoux
- [x] _Qp_qtox
- [ ] _Qp_sqr
- [x] _Qp_stoq
- [x] _Qp_sub
- [x] _Qp_uitoq
- [x] _Qp_uxtoq
- [x] _Qp_xtoq
- [ ] __dtoul (unused in llvm)
- [ ] __ftoul (unused in llvm)

Sidenode
- __dtou64 is alias for fixunsdfdi for ARM

**Comment by andrewrk** [comment]
I'm not seeing the value in this tracking issue.
