### ISSUE TITLE
Tracking 3P: BestEscSeq In The Game

### ISSUE THREAD

**Issue by exxjob** [ziglang/zig#19283]
This one's long overdue; I'm writing an empirical thesis on character encoding, using **ZON** for serializing / declaring various data, because of readability, comments, and nativity. In order of significance on the thesis' behalf:

* [ ] https://github.com/ziglang/zig/issues/14534
* [ ] https://github.com/ziglang/zig/issues/17385 
* [ ]   https://github.com/ziglang/zig/issues/17376 
* [x] https://github.com/ziglang/zig/issues/19381

**Comment by exxjob** [comment]
This seems fairly straight forward. If accepted, I'm happy to make this my first code contribution, granted I'd appreciate guidance if there's a roadblock. Happy to clear up ambiguities if there's left.

**Comment by exxjob** [comment]
I peeked in the source and it seems char literals are a pain point in general. My most recent conclusions:
- Introduce binary and decimal escape sequences (one byte per value cap).
- Rework hexadecimal escape sequence (uncapped), consolidated with UTF-8 escape sequence.
- Escape sequences may chain multiple scalar values.[^1]
- Char literals substituted with a `@u21FromLiteral`.[^2]

### Benefits
- Improved code quality in affected source.
- Fewer ways of doing the same thing in Zig.
- Apostrophes don't need escaping.

[^1]: Zig chars are UTF-8 codepoints, and codepoints can be made of multiple scalars, hence chained values may still be equal to a single codepoint. Checking for invalid codepoints in escape sequences belongs at later stages, if at all. 
[^2]: Char literals don't promote C compatibility; they compel more escape sequences, and to validate a UTF-8 codepoint in literals via `utf8ValidCodepoint` is trivial and more appropriate. Using this to represent the codepoint in whole (as opposed to multiple scalars) is redundant and should be flagged by the compiler for an automatic fix.

**Comment by andrewrk** [comment]
Thank you, please put this on your own issue tracker.
