### ISSUE TITLE
Tracking issue: Building linux kernel

### ISSUE THREAD

**Issue by vesim987** [ziglang/zig#21443]
This is a list of missing features required to build linux kernel:

zig cc:
- [ ] https://github.com/ziglang/zig/blob/master/src/Package/Module.zig#L269-L281
- [ ] `-nostdinc` with `--target=x86_64-linux-gnu` is trying to link glibc(this can be workaround by adding -nostdlib)
- [ ] https://github.com/ziglang/zig/pull/21442

zig objcopy:
- [ ] independence of the host endianness
- [ ] `--remove-section`/`-R`, and also multiple instances of it

There is most likely more hiding behind issues mentioned above.

In the meantime `zig clang` can be used as `CC` and `zig cc` can be used as `HOSTCC`, the biggest issue right now is it the requirement of `llvm-objcopy`/`objcopy`:
```
make CC="zig clang" HOSTCC="zig cc -lc" AR="zig ar" OBJCOPY="llvm-objcopy"
```

**Comment by nektro** [comment]
Related: https://github.com/orgs/ziglang/projects/5
