### ISSUE TITLE
Tracking issue for the LLVM 20 upgrade

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#22014]
We've accumulated a number of issues that should be addressed with LLVM 20, so just opening this as a meta issue to track them all in one place:

- [x] https://github.com/llvm/llvm-project/issues/96432
- [x] https://github.com/llvm/llvm-project/pull/125584
- [x] https://github.com/ziglang/zig/issues/2909
- [x] https://github.com/ziglang/zig/issues/16360
- [x] https://github.com/ziglang/zig/issues/21051
- [x] https://github.com/ziglang/zig/issues/21096
- [x] https://github.com/ziglang/zig/issues/21215
- [x] https://github.com/ziglang/zig/issues/21329
- [x] https://github.com/ziglang/zig/issues/21411
- [x] https://github.com/ziglang/zig/issues/21818
- [x] https://github.com/ziglang/zig/issues/22003
- [x] https://github.com/ziglang/zig/issues/23056
- [x] https://github.com/ziglang/zig/blob/a9c7714b784eeb5e57f6bc718c1e621461dca532/src/codegen/llvm.zig#L273-L274
- [x] https://github.com/ziglang/zig/blob/a9c7714b784eeb5e57f6bc718c1e621461dca532/lib/std/Target.zig#L2266-L2273
