### ISSUE TITLE
Maintain a roadmap for the zig project listing achievements / epic feature groups

### ISSUE THREAD

**Issue by ceymard** [ziglang/zig#3356]
The zig project could really benefit in terms of audience and interest by having a sort of up-to-date roadmap for the big items to come in future releases.

For instance, as an avid user of Typescript, I find myself regularly checking their roadmap page : https://github.com/Microsoft/TypeScript/wiki/Roadmap . It is simple, to the point, and there is a lot of information in very little text. Also, it gets me hyped about what's to come.

I wish something similar would exist for Zig. I also think that many people that stumble upon the project would then gain a sense of how far along it's come and what's to look forward to. This could probably help zig gain even more traction.

While release notes are nice, they're infrequent and a pretty long read. Mostly, people that are already invested into the project will check them. Between release notes, commits tell us more or less what's happening - and they're an even more involved reading. But as far as future plans go, unless you check on IRC and ask people, it's pretty vague.

I say, let's hype it up a notch, and let's do it quickly and efficiently.

Here's a non exhaustive example. Note that there doesn't need to be much more.

# Future

- [ ] ... ?

# 0.7.0 - September 2020

- [ ] working package manager
- [ ] ... ?

# 0.6.0 / master - April 2020

- [ ] self-hosted compiler
- [ ] documentation for `std`
- [ ] std.networking
- [ ] pluggable event loops in std for async/await

# 0.5.0

- [x] Async / await and coroutine rewrite
- [x] SIMD Improvements
- [x] Better C code handling through [*c] pointers
- [x] Result location semantics

# ...

**Comment by andrewrk** [comment]
Each of these release notes has items in their roadmap sections that are still relevant and not completed yet:

 * https://ziglang.org/download/0.3.0/release-notes.html#roadmap
 * https://ziglang.org/download/0.4.0/release-notes.html#Roadmap
 * https://ziglang.org/download/0.5.0/release-notes.html#Roadmap

Predicting 6 months into the future as far as the roadmap is concerned already has a large margin of error. I don't see the benefit of speculating even further into the future.

Have a look at [open and accepted issues](https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Aaccepted).

**Comment by daurnimator** [comment]
I'll also add that you can filter by a milestone *and* accepted:
https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.6.0+label%3Aaccepted

**Comment by ceymard** [comment]
Ok, I did not see the roadmap part (which I actually had read).

But this was not the point ; what I'm saying is that for the uninitiated, the random guy that stumbles here, this crucial information - where is the project going, is not obvious.

I have to scroll down in release notes, or filter issues.

I think that from a communication standpoint, this is not ideal. I mean ; I had to ask to get directions. I *do* try to read up before asking questions, though I admit I'm sometimes in a hurry and miss information. I do not think I'm uniquely moron, so I suppose many people actually come by and miss this bit of information too.

I think that anything that helps communicate more about the projects helps with getting more funding. Right now, it's a little more "RTFM"-ish. :)

A quick fix would maybe add a section on the downloads page, or anywhere quite in view, which would read as more or less ;

# What is zig up to ?

Zig is in constant evolution and a lot of work goes between releases. To have a glimpse of whats coming ;

- Read the current [roadmap](https://ziglang.org/download/0.5.0/release-notes.html#Roadmap)
- Or check the currently [open and accepted proposals](https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.6.0+label%3Aaccepted) that will be implemented soon™

**Comment by andrewrk** [comment]
That looks like a good addition to https://github.com/ziglang/zig/wiki/FAQ

**Comment by ceymard** [comment]
It does.
