### ISSUE TITLE
Tier 1 Support for riscv64-linux

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4456]
Once all these items are complete, we can say that Zig has Tier 1 support for 64-bit RISC-V Linux.

 * [x] make sure we can build-exe with `-target riscv64-linux-gnu`
 * [x] make sure we can build-exe with `-target riscv64-linux-musl`
 * [ ] ability to build libc for riscv64-linux-gnu (#3340)
 * [ ] ability to build libc for riscv64-linux-musl
 * [ ] make sure stack traces / debug info works & [add test coverage](https://github.com/ziglang/zig/blob/master/test/stack_traces.zig)
 * [ ] add the target to the [test matrix](https://github.com/ziglang/zig/blob/40b9db7cad6f876bb3e8fa32d7b32bbd4bc983ea/test/tests.zig#L41-L295)
 * [ ] get the full test suite passing
 * [ ] figure out a risc-v linux continuous integration testing service and hook it up to zig's CI testing.
 * [ ] hook up to update [download page](https://ziglang.org/download/) with risc-v tarballs

Issues to solve:
 * [x] #3478 (solved in llvm10 branch)
 * [ ] #3339 (possibly solved in llvm10 branch? needs investigation)
 * [ ] #3338

**Comment by Ivan-Velickovic** [comment]
`zig build-exe hello.c -lc -target riscv64-linux-musl` with version `0.10.0-dev.3660+4a98385b0` works.

**Comment by RossComputerGuy** [comment]
Looks like traces work, only needs to be added to the test coverage according to the task.

```zig
const std = @import("std");

pub fn a() !void {
    try b();
}

pub fn b() !void {
    try c();
}

pub fn c() !void {
    return error.@"I'm a cat";
}

pub fn main() !void {
    try a();
}
```

```
error: I'm a cat
/home/ross/ExpidusOS/zig/main.zig:12:5: 0x100b5b7 in c (main)
    return error.@"I'm a cat";
    ^
/home/ross/ExpidusOS/zig/main.zig:8:5: 0x100b6d9 in b (main)
    try c();
    ^
/home/ross/ExpidusOS/zig/main.zig:4:5: 0x100b71b in a (main)
    try b();
    ^
/home/ross/ExpidusOS/zig/main.zig:16:5: 0x100b75d in main (main)
    try a();
    ^
```

**Comment by alexrp** [comment]
> * ability to build libc for riscv64-linux-musl

This can be crossed off now:

```console
❯ cat main.zig
const std = @import("std");
pub fn main() !void {
    std.debug.print("Hello, World!\n", .{});
}
❯ ../zig/build/debug/bin/zig build-exe main.zig -target riscv32-linux
❯ ../zig/build/debug/bin/zig build-exe main.zig -target riscv32-linux-musl
❯ ../zig/build/debug/bin/zig build-exe main.zig -target riscv64-linux
❯ ../zig/build/debug/bin/zig build-exe main.zig -target riscv64-linux-musl
```

> figure out a risc-v linux continuous integration testing service and hook it up to zig's CI testing.

Scaleway's pricing looks quite reasonable: https://labs.scaleway.com/en/em-rv1

> Issues to solve:

These are all done.

**Comment by alexrp** [comment]
> ability to build libc for riscv64-linux-gnu

This can also be crossed off as of #20909.

**Comment by alexrp** [comment]
> * add the target to the [test matrix](https://github.com/ziglang/zig/blob/40b9db7cad6f876bb3e8fa32d7b32bbd4bc983ea/test/tests.zig#L41-L295)

This can be crossed off as of the LLVM 19 upgrade.

**Comment by Glavo** [comment]
> figure out a risc-v linux continuous integration testing service and hook it up to zig's CI testing.

Do you need someone to donate some RISC-V physical machines to you?

We are very interested in this and would like to provide some help. Can you provide more detailed requirements?

**Comment by alexrp** [comment]
@Glavo hey, sorry for the super late response. Probably the most important requirement is that we need physical control over the machines that we run CI on.
