### ISSUE TITLE
Zig and Full stack web development

### ISSUE THREAD

**Issue by ansarizafar** [ziglang/zig#942]
As a web developer, I am looking for a fast, memory/cpu efficient and easy to use complied language (Without Stop the World Garbage Collector) for full stack web development like UrWeb http://www.impredicative.com/ur/. Is Zig good for full stack web development? or Is there any plan to do so?

**Comment by andrewrk** [comment]
Zig will be great for full stack web development someday. Here's what the roadmap looks like to get there from here:

 * [ ] finish solving concurrency (see #174)
 * [ ] http server in std lib (see #910)
 * [ ] high quality package manager (see #943)
 * [ ] llvm's web assembly target needs to graduate from experimental. (see https://reviews.llvm.org/D43211)

This use case is an explicit use case that zig wants to handle, it's just a matter of getting there.

**Comment by ansarizafar** [comment]
I am really happy to hear that. I have tried everything from Rust to Crystal and scripting languages from Python to NodeJs/Javascript. Every language has its own set of issues. Rust is very powerful but very complicated. 

It is a great opportunity for any new language and If Zig can do this then combined with a modern database like https://edgedb.com/ https://edgedb.com/blog/edgedb-a-new-beginning  Zig could become an overnight success and rule the web development world in this Progressive Web Apps (PWAs) era.

**Comment by binary132** [comment]
I would like to add that schema-driven (i.e. statically-typed) binary serialization is important to support.  I've recently been thinking about how something like flatbuffers or capnproto could be supported as a feature of a programming language.  Implementing flatbuf support in Zig would be a fun project.

**Comment by catastrop** [comment]
json ?

**Comment by daurnimator** [comment]
> json ?

@catastrop zig already has a json module in the standard library. See `std.json`.

**Comment by catastrop** [comment]
archive, compression ?

**Comment by hryx** [comment]
@catastrop If you want a feature not described in this issue, please open a separate issue. Please take the time to state your question or suggestion clearly.

I'm not sure how to put this delicately, but take note that you won't get far here if you follow [your current style of issues and comments](https://github.com/catastrop); questions and suggestions are welcome as long as they are specific and not already addressed in a separate issue.

**Comment by algoflows** [comment]
Why has this been closed as we've still not got a full-stack web framework!?!

**Comment by mlugg** [comment]
Aside from being pretty subjective, this issue isn't asking for anything in particular, and specific goals (like an HTTP server in std and a package manager) are already covered by other issues, so there's no point leaving this one open. It's worth noting that the package manager is actually starting to see work now that we're on stage2 (andrewrk has been working on writing a good HTTP client into std to start), so we should see some progress here soon. Hopefully https://allyourcodebase.com/webdev/ will be updated and so remain a good reference as the ecosystem progresses.

**Comment by algoflows** [comment]
I see frameworks like Sycamore and Leptos over in the Rust ecosystem for fine grained reactivity frontend frameworks using JSX and Webassembly (think svelte and solidjs in the javascript world). Is there any attempt yet in Zig.

I am keen to have a crack at it but have zero ideas on where to start lol

**Comment by andrewrk** [comment]
Full stack web framework is out of scope for this repository.

**Comment by algoflows** [comment]
Yep totally understand and would imagine it being out of scope. However I am looking to see if I could create a Frontend web framework like Leptos using Zig instead of Rust. Was hoping for a little guidance on any JSX compilation libs in Zig or C that any one knows about?

**Comment by hryx** [comment]
@algoflows Since this issue tracker is focused on bugs and actionable proposals, it's better to pop in to one of the [communities linked in the wiki](https://github.com/ziglang/zig/wiki/Community) for questions and guidance, such as Discord!
